name: home_services_provider
description: Home Service Provider App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.2.7+2
version: 1.2.7+30

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  # GET
  get: ^4.6.5
  get_storage: 2.0.3
  # DIO
  dio: ^4.0.6
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: ^3.0.1
  auto_size_text: 3.0.0
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  material_dialogs: ^1.1.4
  flutter_svg: ^0.23.0+1
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.6
  cupertino_icons: any
  # WEB
  webview_flutter: ^2.8.0
  url_launcher: ^6.1.7
  flutter_html: ^2.2.1
  # FIREBASE
  firebase_messaging: ^14.1.2
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  # GOOGLE MAPS
  google_maps_flutter: ^2.2.1
  map_launcher: ^2.4.0
  rive: ^0.10.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/
    - assets/locales/
    - assets/RiveAssets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
